package(
    default_visibility = ["//:__subpackages__"],
)

# https://docs.bazel.build/versions/master/be/android.html#android_binary
android_binary(
    name = "debug_app",
    manifest = "AndroidManifest.xml",
    deps = ["//src/main/java/com/example/android/app"],
)

